name: "Build and Create Draft Release"

on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        strategy:
            matrix:
                platform: [ubuntu-latest]
        runs-on: ${{matrix.platform}}
        steps:
            - name: Checkout this repo
              uses: actions/checkout/@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Install webkit2gtk and zip (ubuntu environment only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webkit2gtk-4.0 jq zip

            - name: Install dependencies using Yarn
              run: yarn install

            - name: Build using Yarn command
              run: yarn build

            - name: Read version from update.json
              run: |
                  echo 'UPDATE_JSON << EOF' >> $GITHUB_ENV
                  cat ./src-tauri/update.json >> $GITHUB_ENV
                  echo 'EOF' >> $GITHUB_ENV

            - name: Create the zip file
              run: |
                  file_name="Granblue Automation v${{fromJson(env.UPDATE_JSON).version}}.zip"
                  echo "VERSION=v${{fromJson(env.UPDATE_JSON).version}}" >> $GITHUB_ENV
                  echo "FILE_NAME=${file_name}" >> $GITHUB_ENV
                  echo "${{env.FILE_NAME}}"
                  cd ./src-tauri/target/release
                  zip -r ${file_name} backend images scripts Granblue\ Automation.exe

            - name: Create Draft Release
              uses: softprops/action-gh-release@v1
              with:
                  name: ${{env.VERSION}}
                  drafts: true
                  files: |
                      ./src-tauri/target/release/${{env.FILE_NAME}}
