name: "Build and Create Draft Release"

on:
    workflow_dispatch:

permissions:
    contents: write

env:
    TAURI_PRIVATE_KEY: ${{secrets.TAURI_PRIVATE_KEY}}

jobs:
    build-and-deploy:
        strategy:
            matrix:
                platform: [windows-latest]
        runs-on: ${{matrix.platform}}
        steps:
            - name: Checkout this repo
              uses: actions/checkout/@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Install webkit2gtk and zip (ubuntu environment only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webkit2gtk-4.0 jq zip

            - name: Install dependencies using Yarn
              run: yarn install

            - name: Build using Yarn command
              run: yarn build

            - name: Get version from update.json
              id: version-getter
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: ./src-tauri/update.json
                  prop_path: version

            - name: Set version to env
              run: echo "VERSION=v${{steps.version-getter.outputs.prop}}" >> $GITHUB_ENV

            - name: Create the zip file (windows)
              if: matrix.platform == 'windows-latest'
              run: |
                  file_name="Granblue Automation ${{env.VERSION}}.zip"
                  echo "FILE_NAME=${file_name}" >> $GITHUB_ENV
                  echo "${{env.FILE_NAME}}"
                  cd ./src-tauri/target/release
                  Compress-Archive -Path 'backend','images','scripts','./Granblue Automation.exe' -DestinationPath './Granblue Automation.zip'

            - name: Create the zip file (ubuntu)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  file_name="Granblue Automation ${{env.VERSION}}.zip"
                  echo "FILE_NAME=${file_name}" >> $GITHUB_ENV
                  echo "${{env.FILE_NAME}}"
                  cd ./src-tauri/target/release
                  zip -r "${file_name}" backend images scripts Granblue\ Automation.exe

            - name: Create Draft Release
              uses: softprops/action-gh-release@v1
              with:
                  name: ${{env.VERSION}}
                  tag_name: ${{env.VERSION}}
                  draft: true
                  files: |
                      ./src-tauri/target/release/${{env.FILE_NAME}}
